// ============================================================================
// src/components/ingest/processing-orbit.tsx
//
// The hero of the processing screen: the supplied orbit animation with its
// gear cluster replaced by the Winback mark, exactly as asked. Everything else
// in that file is the original — the orbiting product marks, the counter-
// rotating rings, the original timing.
//
// Served as a plain <img>. The animation is SMIL inside the SVG, which browsers
// run without any player, so this costs one cached request and no JavaScript.
// Generated by scripts/build-orbit-svg.ts from design/reference/.
//
// It is decorative and marked so: the real state lives in the stepper, the
// stage line and the document list beside it, all of which a screen reader
// reads. This never becomes the only thing telling a user what is happening.
// ============================================================================

export interface ProcessingOrbitProps {
  size?: number;
}

export function ProcessingOrbit({ size = 300 }: ProcessingOrbitProps) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/anim/orbit-winback.svg"
      alt=""
      aria-hidden="true"
      width={size}
      height={size}
      style={{ display: 'block', margin: '0 auto', maxWidth: '100%' }}
    />
  );
}
